In [7]:
import pandas as pd

In [1]:
GCP_PROJECT = "seagrass-lewagon"
GCP_REGION="europe-west1"
BQ_DATASET = "seagrass"

In [4]:
query = f"""
    SELECT *
    FROM `{GCP_PROJECT}.{BQ_DATASET}.merged_features`
    """

In [2]:
! pwd

/Users/rafa/code/Rafapizarro/seagrass

In [6]:
from google.cloud import bigquery

client = bigquery.Client(project=GCP_PROJECT)
query_job = client.query(query)
result = query_job.result()
merged_features = result.to_dataframe()
merged_features.to_csv("data/merged_features.csv", header=True, index=False)

In [9]:
merged_features = pd.read_csv("data/merged_features.csv")
merged_features

,lat,lon,po4,no3,si,nh4,bottom_temp,chlorophyll,avg_temp,salinity,depth
0,30.3125,19.2083,0.004740,0.051770,2.718759,0.025912,22.069154,-0.604708,22.136564,38.917587,-0.350525
1,30.3125,19.0000,0.004753,0.050061,2.729147,0.025394,22.162248,-0.722136,22.209953,38.972239,-0.350794
2,30.3542,19.2500,0.004700,0.050400,2.751623,0.027028,21.827729,-0.297430,22.157374,38.814760,-0.351566
3,30.3542,19.4167,0.004698,0.053587,2.712808,0.027708,21.997698,-1.146987,22.087574,38.823783,-0.351150
4,30.3542,18.9583,0.004712,0.047527,2.762069,0.025768,22.072648,-0.344697,22.249211,38.893303,-0.351799
...,...,...,...,...,...,...,...,...,...,...,...
96512,45.6458,13.4167,0.017160,4.179916,5.616475,0.470007,17.324449,-0.495972,16.857247,36.523517,-0.460568
96513,45.6458,13.4583,0.018525,5.002612,6.025208,0.506424,17.275804,-0.923330,16.805123,36.621604,-0.461311
96514,45.6458,13.1667,0.026258,4.307854,5.868522,0.534417,17.319293,-0.552241,16.894640,36.188888,-0.455058
96515,45.6458,13.7083,0.029593,9.241012,8.483284,0.823492,16.308663,-0.639466,16.808206,37.649041,-0.469226
96516,45.6458,13.5000,0.021731,5.914501,6.591555,0.572491,17.060652,-0.927391,16.815045,36.880559,-0.462862

In [10]:
import folium

In [12]:
# Define the center of the Mediterranean for the map
mediterranean_center = [34.5, 18.0]  # Approximate central coordinates

# Create a Folium map
m = folium.Map(location=mediterranean_center, zoom_start=5)

# Add points to the map
for _, row in merged_features.iterrows():
    folium.CircleMarker(
        location=[row["lat"], row["lon"]],
        radius=2,  # Small dot for each point
        color="blue",
        fill=True,
        fill_color="blue",
        fill_opacity=0.6
    ).add_to(m)

# Save and display the map
m.save("mediterranean_map.html")
print("âœ… Map saved as 'mediterranean_map.html'. Open it in a browser to view.")

âœ… Map saved as 'mediterranean_map.html'. Open it in a browser to view.